name: tweede golf

# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty

# Server
destination: ./_site
exclude:
    - .gitignore
    - README.md
    - bower.json
    - .bowerrc
    - docker-compose.yml
    - Vagrantfile

collections:
    portfolio:
        output: false
    static:
        output: true
    cases:
        output: false
    cubes:
        output: false
    members:
        output: false
