name: tweede golf
markdown: kramdown
permalink: pretty
destination: ./_site

sass:
  load_paths:
    - _sass
    - vendor/bootstrap-sass-twbs/assets/stylesheets

exclude:
  - .bowerrc
  - .jekyll-metadata
  - .gitignore
  - bower.json
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - Vagrantfile

include:
  - _pages

collections:
  portfolio:
    output: false
  static:
    output: true
  cases:
    output: false
  cubes:
    output: false
  members:
    output: false
