name: tweede golf
markdown: kramdown
permalink: pretty
destination: ./_site

exclude:
  - .bowerrc
  - .jekyll-metadata
  - .gitignore
  - bower.json
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - sass
  - Vagrantfile

include:
  - _pages

collections:
  portfolio:
    output: false
  static:
    output: true
  cases:
    output: false
  cubes:
    output: false
  members:
    output: false
