name: tweede golf
kvk: "09202176"
btw: NL820951183B01
iban: NL27ABNA0551876433
markdown: kramdown
permalink: pretty
destination: ./_site

exclude:
  - bower.json
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - sass
  - Vagrantfile

include:
  - _pages

collections:
  portfolio:
    output: false
  static:
    output: true
  cases:
    output: false
  members:
    output: false
